development:
  host: localhost
  database: sogoke_instance_development

test:
  host: localhost
  database: sogoke_instance_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>