require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BuzzsController do

  # This should return the minimal set of attributes required to create a valid
  # Buzz. As you add validations to Buzz, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all buzzs as @buzzs" do
      buzz = Buzz.create! valid_attributes
      get :index
      assigns(:buzzs).should eq([buzz])
    end
  end

  describe "GET show" do
    it "assigns the requested buzz as @buzz" do
      buzz = Buzz.create! valid_attributes
      get :show, :id => buzz.id.to_s
      assigns(:buzz).should eq(buzz)
    end
  end

  describe "GET new" do
    it "assigns a new buzz as @buzz" do
      get :new
      assigns(:buzz).should be_a_new(Buzz)
    end
  end

  describe "GET edit" do
    it "assigns the requested buzz as @buzz" do
      buzz = Buzz.create! valid_attributes
      get :edit, :id => buzz.id.to_s
      assigns(:buzz).should eq(buzz)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Buzz" do
        expect {
          post :create, :buzz => valid_attributes
        }.to change(Buzz, :count).by(1)
      end

      it "assigns a newly created buzz as @buzz" do
        post :create, :buzz => valid_attributes
        assigns(:buzz).should be_a(Buzz)
        assigns(:buzz).should be_persisted
      end

      it "redirects to the created buzz" do
        post :create, :buzz => valid_attributes
        response.should redirect_to(Buzz.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved buzz as @buzz" do
        # Trigger the behavior that occurs when invalid params are submitted
        Buzz.any_instance.stub(:save).and_return(false)
        post :create, :buzz => {}
        assigns(:buzz).should be_a_new(Buzz)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Buzz.any_instance.stub(:save).and_return(false)
        post :create, :buzz => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested buzz" do
        buzz = Buzz.create! valid_attributes
        # Assuming there are no other buzzs in the database, this
        # specifies that the Buzz created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Buzz.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => buzz.id, :buzz => {'these' => 'params'}
      end

      it "assigns the requested buzz as @buzz" do
        buzz = Buzz.create! valid_attributes
        put :update, :id => buzz.id, :buzz => valid_attributes
        assigns(:buzz).should eq(buzz)
      end

      it "redirects to the buzz" do
        buzz = Buzz.create! valid_attributes
        put :update, :id => buzz.id, :buzz => valid_attributes
        response.should redirect_to(buzz)
      end
    end

    describe "with invalid params" do
      it "assigns the buzz as @buzz" do
        buzz = Buzz.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Buzz.any_instance.stub(:save).and_return(false)
        put :update, :id => buzz.id.to_s, :buzz => {}
        assigns(:buzz).should eq(buzz)
      end

      it "re-renders the 'edit' template" do
        buzz = Buzz.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Buzz.any_instance.stub(:save).and_return(false)
        put :update, :id => buzz.id.to_s, :buzz => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested buzz" do
      buzz = Buzz.create! valid_attributes
      expect {
        delete :destroy, :id => buzz.id.to_s
      }.to change(Buzz, :count).by(-1)
    end

    it "redirects to the buzzs list" do
      buzz = Buzz.create! valid_attributes
      delete :destroy, :id => buzz.id.to_s
      response.should redirect_to(buzzs_url)
    end
  end

end
